language: php
php:
  - '7.3'
  - '7.4'

branches:
  only:
    - master

before_install:
  - composer self-update
  - composer validate --ansi

install:
  - rm composer.lock
  - travis_retry composer update --prefer-dist

script:
  - composer phpstan
  - composer phpunit
